package com.blucharge.puppet.enums;

public enum ChargePointErrorCode {
    CONNECTORLOCKFAILURE, EVCOMMUNICATIONERROR, GROUNDFAILURE, HIGHTEMPERATURE, INTERNALERROR, LOCALLISTCONFLICT,
    NOERROR, OTHERERROR, OVERCURRENTFAILURE, OVERVOLTAGE, POWERMETERFAILURE, POWERSWITCHFAILURE, READERFAILURE,
    RESETFAILURE, UNDERVOLTAGE, WEAKSIGNAL
}
