package com.blucharge.puppet.enums;

public enum ReasonForStopTransaction {
    EMERGENCYSTOP, EVDISCONNECTED, HARDRESET, LOCAL, OTHER, POWERLOSS, REBOOT,
    REMOTE, SOFTRESET, UNLOCKCOMMAND, DEAUTHORIZED
}
