package com.blucharge.puppet.dto.enums;

public enum ChargePointErrorCode {
    CONNECTORLOCKFAILURE, EVCOMMUNICATIONERROR, GROUNDFAILURE, HIGHTEMPERATURE, INTERNALERROR, LOCALLISTCONFLICT,
    N0ERROR, OTHERERROR, OVERCURRENTFAILURE, OVERVOLTAGE, POWERMETERFAILURE, POWERSWITCHFAILURE, READERFAILURE,
    RESETFAILURE, UNDERVOLTAGE, WEAKSIGNAL

}
